### PR TITLE
Options for changing icon border and fill color

### PR DESCRIPTION
**Pull request by bfeldkamp3**
Added in options for changing the default colors by passing in borderColor and/or fillColor. Uses jQuery.css() to add a 'color' style based on the (de)selected icons.

### CODE REVIEW

**Comment by jvv** [comment]
Thanks for the pull request - The thought I'm having is this: wouldn't it be easier to add a 'selected' class to those who are selected and just overwrite the color in the CSS file? Let me know what you think.

**Comment by bfeldkamp3** [comment]
I agree! That does sound like a better solution. Updated to reflect that.

**Comment by bfeldkamp3** [comment]
I updated the README to document the change. Let me know if you see any other issues!

**Comment by jvv** [comment]
Merged, thanks for your time :)

**Pull request merged**
